#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : redis-native
Version  : 4.0.11
Release  : 21
URL      : http://download.redis.io/releases/redis-4.0.11.tar.gz
Source0  : http://download.redis.io/releases/redis-4.0.11.tar.gz
Summary  : An Extensible Extension Language
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause MIT
Requires: redis-native-bin
Requires: redis-native-license
BuildRequires : jemalloc-dev
BuildRequires : lua-dev
BuildRequires : procps-ng
BuildRequires : tcl
Patch1: 0001-Use-O3-optimization.patch
Patch2: 0002-Install-to-usr-honor-DESTDIR-for-install.patch
Patch3: 0003-Set-release-timestamp-to-SOURCE_DATE_EPOCH.patch

%description
The test-lru.rb program can be used in order to check the behavior of the
Redis approximated LRU algorithm against the theoretical output of true
LRU algorithm.

%package bin
Summary: bin components for the redis-native package.
Group: Binaries
Requires: redis-native-license

%description bin
bin components for the redis-native package.


%package license
Summary: license components for the redis-native package.
Group: Default

%description license
license components for the redis-native package.


%prep
%setup -q -n redis-4.0.11
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533312865
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
make  %{?_smp_mflags} MALLOC=libc

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make -C src %{_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1533312865
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/redis-native
cp COPYING %{buildroot}/usr/share/doc/redis-native/COPYING
cp deps/hiredis/COPYING %{buildroot}/usr/share/doc/redis-native/deps_hiredis_COPYING
cp deps/jemalloc/COPYING %{buildroot}/usr/share/doc/redis-native/deps_jemalloc_COPYING
cp deps/lua/COPYRIGHT %{buildroot}/usr/share/doc/redis-native/deps_lua_COPYRIGHT
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/redis-benchmark
/usr/bin/redis-check-aof
/usr/bin/redis-check-rdb
/usr/bin/redis-cli
/usr/bin/redis-sentinel
/usr/bin/redis-server

%files license
%defattr(-,root,root,-)
/usr/share/doc/redis-native/COPYING
/usr/share/doc/redis-native/deps_hiredis_COPYING
/usr/share/doc/redis-native/deps_jemalloc_COPYING
/usr/share/doc/redis-native/deps_lua_COPYRIGHT
