#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : redis-native
Version  : 3.2.0
Release  : 8
URL      : http://download.redis.io/releases/redis-3.2.0.tar.gz
Source0  : http://download.redis.io/releases/redis-3.2.0.tar.gz
Summary  : An Extensible Extension Language
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause MIT
Requires: redis-native-bin
BuildRequires : jemalloc-dev
BuildRequires : lua-dev
Patch1: build_3.20.patch

%description
The test-lru.rb program can be used in order to check the behavior of the
Redis approximated LRU algorithm against the theoretical output of true
LRU algorithm.

%package bin
Summary: bin components for the redis-native package.
Group: Binaries

%description bin
bin components for the redis-native package.


%prep
%setup -q -n redis-3.2.0
%patch1 -p1

%build
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/redis-benchmark
/usr/bin/redis-check-aof
/usr/bin/redis-check-rdb
/usr/bin/redis-cli
/usr/bin/redis-sentinel
/usr/bin/redis-server
